regions = {
    "Farg'ona": "fergana",
    'Namangan': 'namangan',
    'Andijon': 'andijon',
    'Toshkent sh': 'tashkent city',
    'Toshkent vil': 'tashkent region',
    'Sirdaryo': 'sirdarya',
    'Jizzax': 'jizzakh',
    'Samarqand': 'samarkand',
    'Buxoro': 'bukhara',
    'Navoiy': 'navai',
    'Qashqadaryo': 'kashkadarya',
    'Surxondaryo': 'surkhandarya',
    'Xorazm': 'khorezm',
    "Qoraqalpog'iston": "karakalpakistan",
}
