# Generated by Django 4.2.7 on 2024-03-31 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date of last modification')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.PositiveBigIntegerField(default=1, unique=True, verbose_name='telegram id')),
                ('is_fake', models.BooleanField(blank=True, default=False, null=True, verbose_name='is fake')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='full name')),
                ('phone_number', models.BigIntegerField(blank=True, null=True, verbose_name='phone number')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='telegram username')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='age')),
                ('sex', models.CharField(blank=True, max_length=30, null=True, verbose_name="user's sex")),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name="user's location")),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='height')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='weight')),
                ('ethnicity', models.CharField(blank=True, max_length=255, null=True, verbose_name='ethnicity')),
                ('marital_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='marital status')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='education')),
                ('occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='occupation')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='biography')),
                ('photo_id', models.CharField(max_length=400, null=True, verbose_name='Photo_ID')),
                ('need_partner_age_min', models.PositiveIntegerField(default=18, verbose_name='minimum partner age')),
                ('need_partner_age_max', models.PositiveIntegerField(default=78, verbose_name='maximum partner age')),
            ],
            options={
                'verbose_name': ('Dating User',),
                'verbose_name_plural': 'Dating Users',
            },
        ),
        migrations.CreateModel(
            name='ViewedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='tgbot.user')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer', to='tgbot.user')),
            ],
            options={
                'unique_together': {('viewer', 'profile')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='viewed_profiles',
            field=models.ManyToManyField(through='tgbot.ViewedProfile', to='tgbot.user'),
        ),
    ]
