# Generated by Django 4.2.7 on 2024-04-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
