# Generated by Django 4.2.7 on 2024-04-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_user_notification_sent_alter_viewedprofile_viewer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NecessaryLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date of last modification')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField(verbose_name='Majburiy havola')),
                ('telegram_link_id', models.BigIntegerField(verbose_name="Kanal/chatning id'si")),
                ('title', models.CharField(max_length=50, verbose_name="Tugma nomi, emoji ishlatsa ham bo'ladi")),
            ],
            options={
                'verbose_name': 'Majburiy havola',
                'verbose_name_plural': 'Majburiy havolalar',
            },
        ),
    ]
