# Generated by Django 4.2.7 on 2024-04-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_referral_user_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_sent',
        ),
    ]
